// Code generated by "enumer -type EntityType -trimprefix EntityMsg -json"; DO NOT EDIT.

package tradovate

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EntityTypeName = "EntityTypeUnspecifiedEntityTypeAccountEntityTypeAccountRiskStatusEntityTypeAdminAlertEntityTypeAdminAlertSignalEntityTypeCashBalanceEntityTypeCashBalanceLogEntityTypeChatEntityTypeChatMessageEntityTypeClearingHouseEntityTypeCommandEntityTypeCommandReportEntityTypeContactInfoEntityTypeContractEntityTypeContractGroupEntityTypeContractMarginEntityTypeContractMaturityEntityTypeCurrencyEntityTypeCurrencyRateEntityTypeEntitlementEntityTypeExchangeEntityTypeExecutionReportEntityTypeFillEntityTypeFillFeeEntityTypeFillPairEntityTypeMarginSnapshotEntityTypeMarketDataSubscriptionEntityTypeMarketDataSubscriptionExchangeScopeEntityTypeMarketDataSubscriptionPlanEntityTypeOrderEntityTypeOrderStrategyEntityTypeOrderStrategyLinkEntityTypeOrderStrategyTypeEntityTypeOrderVersionEntityTypeOrganizationEntityTypePermissionedAccountAutoLiqEntityTypePositionEntityTypeProductEntityTypeProductMarginEntityTypeProductSessionEntityTypePropertyEntityTypeSecondMarketDataSubscriptionEntityTypeSpreadDefinitionEntityTypeTradingPermissionEntityTypeTradovateSubscriptionEntityTypeTradovateSubscriptionPlanEntityTypeUserEntityTypeUserAccountAutoLiqEntityTypeUserAccountPositionLimitEntityTypeUserAccountRiskParameterEntityTypeUserPluginEntityTypeUserPropertyEntityTypeUserSessionEntityTypeUserSessionStats"

var _EntityTypeIndex = [...]uint16{0, 21, 38, 65, 85, 111, 132, 156, 170, 191, 214, 231, 254, 275, 293, 316, 340, 366, 384, 406, 427, 445, 470, 484, 501, 519, 543, 575, 620, 656, 671, 694, 721, 748, 770, 792, 828, 846, 863, 886, 910, 928, 966, 992, 1019, 1050, 1085, 1099, 1127, 1161, 1195, 1215, 1237, 1258, 1284}

const _EntityTypeLowerName = "entitytypeunspecifiedentitytypeaccountentitytypeaccountriskstatusentitytypeadminalertentitytypeadminalertsignalentitytypecashbalanceentitytypecashbalancelogentitytypechatentitytypechatmessageentitytypeclearinghouseentitytypecommandentitytypecommandreportentitytypecontactinfoentitytypecontractentitytypecontractgroupentitytypecontractmarginentitytypecontractmaturityentitytypecurrencyentitytypecurrencyrateentitytypeentitlemententitytypeexchangeentitytypeexecutionreportentitytypefillentitytypefillfeeentitytypefillpairentitytypemarginsnapshotentitytypemarketdatasubscriptionentitytypemarketdatasubscriptionexchangescopeentitytypemarketdatasubscriptionplanentitytypeorderentitytypeorderstrategyentitytypeorderstrategylinkentitytypeorderstrategytypeentitytypeorderversionentitytypeorganizationentitytypepermissionedaccountautoliqentitytypepositionentitytypeproductentitytypeproductmarginentitytypeproductsessionentitytypepropertyentitytypesecondmarketdatasubscriptionentitytypespreaddefinitionentitytypetradingpermissionentitytypetradovatesubscriptionentitytypetradovatesubscriptionplanentitytypeuserentitytypeuseraccountautoliqentitytypeuseraccountpositionlimitentitytypeuseraccountriskparameterentitytypeuserpluginentitytypeuserpropertyentitytypeusersessionentitytypeusersessionstats"

func (i EntityType) String() string {
	if i >= EntityType(len(_EntityTypeIndex)-1) {
		return fmt.Sprintf("EntityType(%d)", i)
	}
	return _EntityTypeName[_EntityTypeIndex[i]:_EntityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EntityTypeNoOp() {
	var x [1]struct{}
	_ = x[EntityTypeUnspecified-(0)]
	_ = x[EntityTypeAccount-(1)]
	_ = x[EntityTypeAccountRiskStatus-(2)]
	_ = x[EntityTypeAdminAlert-(3)]
	_ = x[EntityTypeAdminAlertSignal-(4)]
	_ = x[EntityTypeCashBalance-(5)]
	_ = x[EntityTypeCashBalanceLog-(6)]
	_ = x[EntityTypeChat-(7)]
	_ = x[EntityTypeChatMessage-(8)]
	_ = x[EntityTypeClearingHouse-(9)]
	_ = x[EntityTypeCommand-(10)]
	_ = x[EntityTypeCommandReport-(11)]
	_ = x[EntityTypeContactInfo-(12)]
	_ = x[EntityTypeContract-(13)]
	_ = x[EntityTypeContractGroup-(14)]
	_ = x[EntityTypeContractMargin-(15)]
	_ = x[EntityTypeContractMaturity-(16)]
	_ = x[EntityTypeCurrency-(17)]
	_ = x[EntityTypeCurrencyRate-(18)]
	_ = x[EntityTypeEntitlement-(19)]
	_ = x[EntityTypeExchange-(20)]
	_ = x[EntityTypeExecutionReport-(21)]
	_ = x[EntityTypeFill-(22)]
	_ = x[EntityTypeFillFee-(23)]
	_ = x[EntityTypeFillPair-(24)]
	_ = x[EntityTypeMarginSnapshot-(25)]
	_ = x[EntityTypeMarketDataSubscription-(26)]
	_ = x[EntityTypeMarketDataSubscriptionExchangeScope-(27)]
	_ = x[EntityTypeMarketDataSubscriptionPlan-(28)]
	_ = x[EntityTypeOrder-(29)]
	_ = x[EntityTypeOrderStrategy-(30)]
	_ = x[EntityTypeOrderStrategyLink-(31)]
	_ = x[EntityTypeOrderStrategyType-(32)]
	_ = x[EntityTypeOrderVersion-(33)]
	_ = x[EntityTypeOrganization-(34)]
	_ = x[EntityTypePermissionedAccountAutoLiq-(35)]
	_ = x[EntityTypePosition-(36)]
	_ = x[EntityTypeProduct-(37)]
	_ = x[EntityTypeProductMargin-(38)]
	_ = x[EntityTypeProductSession-(39)]
	_ = x[EntityTypeProperty-(40)]
	_ = x[EntityTypeSecondMarketDataSubscription-(41)]
	_ = x[EntityTypeSpreadDefinition-(42)]
	_ = x[EntityTypeTradingPermission-(43)]
	_ = x[EntityTypeTradovateSubscription-(44)]
	_ = x[EntityTypeTradovateSubscriptionPlan-(45)]
	_ = x[EntityTypeUser-(46)]
	_ = x[EntityTypeUserAccountAutoLiq-(47)]
	_ = x[EntityTypeUserAccountPositionLimit-(48)]
	_ = x[EntityTypeUserAccountRiskParameter-(49)]
	_ = x[EntityTypeUserPlugin-(50)]
	_ = x[EntityTypeUserProperty-(51)]
	_ = x[EntityTypeUserSession-(52)]
	_ = x[EntityTypeUserSessionStats-(53)]
}

var _EntityTypeValues = []EntityType{EntityTypeUnspecified, EntityTypeAccount, EntityTypeAccountRiskStatus, EntityTypeAdminAlert, EntityTypeAdminAlertSignal, EntityTypeCashBalance, EntityTypeCashBalanceLog, EntityTypeChat, EntityTypeChatMessage, EntityTypeClearingHouse, EntityTypeCommand, EntityTypeCommandReport, EntityTypeContactInfo, EntityTypeContract, EntityTypeContractGroup, EntityTypeContractMargin, EntityTypeContractMaturity, EntityTypeCurrency, EntityTypeCurrencyRate, EntityTypeEntitlement, EntityTypeExchange, EntityTypeExecutionReport, EntityTypeFill, EntityTypeFillFee, EntityTypeFillPair, EntityTypeMarginSnapshot, EntityTypeMarketDataSubscription, EntityTypeMarketDataSubscriptionExchangeScope, EntityTypeMarketDataSubscriptionPlan, EntityTypeOrder, EntityTypeOrderStrategy, EntityTypeOrderStrategyLink, EntityTypeOrderStrategyType, EntityTypeOrderVersion, EntityTypeOrganization, EntityTypePermissionedAccountAutoLiq, EntityTypePosition, EntityTypeProduct, EntityTypeProductMargin, EntityTypeProductSession, EntityTypeProperty, EntityTypeSecondMarketDataSubscription, EntityTypeSpreadDefinition, EntityTypeTradingPermission, EntityTypeTradovateSubscription, EntityTypeTradovateSubscriptionPlan, EntityTypeUser, EntityTypeUserAccountAutoLiq, EntityTypeUserAccountPositionLimit, EntityTypeUserAccountRiskParameter, EntityTypeUserPlugin, EntityTypeUserProperty, EntityTypeUserSession, EntityTypeUserSessionStats}

var _EntityTypeNameToValueMap = map[string]EntityType{
	_EntityTypeName[0:21]:           EntityTypeUnspecified,
	_EntityTypeLowerName[0:21]:      EntityTypeUnspecified,
	_EntityTypeName[21:38]:          EntityTypeAccount,
	_EntityTypeLowerName[21:38]:     EntityTypeAccount,
	_EntityTypeName[38:65]:          EntityTypeAccountRiskStatus,
	_EntityTypeLowerName[38:65]:     EntityTypeAccountRiskStatus,
	_EntityTypeName[65:85]:          EntityTypeAdminAlert,
	_EntityTypeLowerName[65:85]:     EntityTypeAdminAlert,
	_EntityTypeName[85:111]:         EntityTypeAdminAlertSignal,
	_EntityTypeLowerName[85:111]:    EntityTypeAdminAlertSignal,
	_EntityTypeName[111:132]:        EntityTypeCashBalance,
	_EntityTypeLowerName[111:132]:   EntityTypeCashBalance,
	_EntityTypeName[132:156]:        EntityTypeCashBalanceLog,
	_EntityTypeLowerName[132:156]:   EntityTypeCashBalanceLog,
	_EntityTypeName[156:170]:        EntityTypeChat,
	_EntityTypeLowerName[156:170]:   EntityTypeChat,
	_EntityTypeName[170:191]:        EntityTypeChatMessage,
	_EntityTypeLowerName[170:191]:   EntityTypeChatMessage,
	_EntityTypeName[191:214]:        EntityTypeClearingHouse,
	_EntityTypeLowerName[191:214]:   EntityTypeClearingHouse,
	_EntityTypeName[214:231]:        EntityTypeCommand,
	_EntityTypeLowerName[214:231]:   EntityTypeCommand,
	_EntityTypeName[231:254]:        EntityTypeCommandReport,
	_EntityTypeLowerName[231:254]:   EntityTypeCommandReport,
	_EntityTypeName[254:275]:        EntityTypeContactInfo,
	_EntityTypeLowerName[254:275]:   EntityTypeContactInfo,
	_EntityTypeName[275:293]:        EntityTypeContract,
	_EntityTypeLowerName[275:293]:   EntityTypeContract,
	_EntityTypeName[293:316]:        EntityTypeContractGroup,
	_EntityTypeLowerName[293:316]:   EntityTypeContractGroup,
	_EntityTypeName[316:340]:        EntityTypeContractMargin,
	_EntityTypeLowerName[316:340]:   EntityTypeContractMargin,
	_EntityTypeName[340:366]:        EntityTypeContractMaturity,
	_EntityTypeLowerName[340:366]:   EntityTypeContractMaturity,
	_EntityTypeName[366:384]:        EntityTypeCurrency,
	_EntityTypeLowerName[366:384]:   EntityTypeCurrency,
	_EntityTypeName[384:406]:        EntityTypeCurrencyRate,
	_EntityTypeLowerName[384:406]:   EntityTypeCurrencyRate,
	_EntityTypeName[406:427]:        EntityTypeEntitlement,
	_EntityTypeLowerName[406:427]:   EntityTypeEntitlement,
	_EntityTypeName[427:445]:        EntityTypeExchange,
	_EntityTypeLowerName[427:445]:   EntityTypeExchange,
	_EntityTypeName[445:470]:        EntityTypeExecutionReport,
	_EntityTypeLowerName[445:470]:   EntityTypeExecutionReport,
	_EntityTypeName[470:484]:        EntityTypeFill,
	_EntityTypeLowerName[470:484]:   EntityTypeFill,
	_EntityTypeName[484:501]:        EntityTypeFillFee,
	_EntityTypeLowerName[484:501]:   EntityTypeFillFee,
	_EntityTypeName[501:519]:        EntityTypeFillPair,
	_EntityTypeLowerName[501:519]:   EntityTypeFillPair,
	_EntityTypeName[519:543]:        EntityTypeMarginSnapshot,
	_EntityTypeLowerName[519:543]:   EntityTypeMarginSnapshot,
	_EntityTypeName[543:575]:        EntityTypeMarketDataSubscription,
	_EntityTypeLowerName[543:575]:   EntityTypeMarketDataSubscription,
	_EntityTypeName[575:620]:        EntityTypeMarketDataSubscriptionExchangeScope,
	_EntityTypeLowerName[575:620]:   EntityTypeMarketDataSubscriptionExchangeScope,
	_EntityTypeName[620:656]:        EntityTypeMarketDataSubscriptionPlan,
	_EntityTypeLowerName[620:656]:   EntityTypeMarketDataSubscriptionPlan,
	_EntityTypeName[656:671]:        EntityTypeOrder,
	_EntityTypeLowerName[656:671]:   EntityTypeOrder,
	_EntityTypeName[671:694]:        EntityTypeOrderStrategy,
	_EntityTypeLowerName[671:694]:   EntityTypeOrderStrategy,
	_EntityTypeName[694:721]:        EntityTypeOrderStrategyLink,
	_EntityTypeLowerName[694:721]:   EntityTypeOrderStrategyLink,
	_EntityTypeName[721:748]:        EntityTypeOrderStrategyType,
	_EntityTypeLowerName[721:748]:   EntityTypeOrderStrategyType,
	_EntityTypeName[748:770]:        EntityTypeOrderVersion,
	_EntityTypeLowerName[748:770]:   EntityTypeOrderVersion,
	_EntityTypeName[770:792]:        EntityTypeOrganization,
	_EntityTypeLowerName[770:792]:   EntityTypeOrganization,
	_EntityTypeName[792:828]:        EntityTypePermissionedAccountAutoLiq,
	_EntityTypeLowerName[792:828]:   EntityTypePermissionedAccountAutoLiq,
	_EntityTypeName[828:846]:        EntityTypePosition,
	_EntityTypeLowerName[828:846]:   EntityTypePosition,
	_EntityTypeName[846:863]:        EntityTypeProduct,
	_EntityTypeLowerName[846:863]:   EntityTypeProduct,
	_EntityTypeName[863:886]:        EntityTypeProductMargin,
	_EntityTypeLowerName[863:886]:   EntityTypeProductMargin,
	_EntityTypeName[886:910]:        EntityTypeProductSession,
	_EntityTypeLowerName[886:910]:   EntityTypeProductSession,
	_EntityTypeName[910:928]:        EntityTypeProperty,
	_EntityTypeLowerName[910:928]:   EntityTypeProperty,
	_EntityTypeName[928:966]:        EntityTypeSecondMarketDataSubscription,
	_EntityTypeLowerName[928:966]:   EntityTypeSecondMarketDataSubscription,
	_EntityTypeName[966:992]:        EntityTypeSpreadDefinition,
	_EntityTypeLowerName[966:992]:   EntityTypeSpreadDefinition,
	_EntityTypeName[992:1019]:       EntityTypeTradingPermission,
	_EntityTypeLowerName[992:1019]:  EntityTypeTradingPermission,
	_EntityTypeName[1019:1050]:      EntityTypeTradovateSubscription,
	_EntityTypeLowerName[1019:1050]: EntityTypeTradovateSubscription,
	_EntityTypeName[1050:1085]:      EntityTypeTradovateSubscriptionPlan,
	_EntityTypeLowerName[1050:1085]: EntityTypeTradovateSubscriptionPlan,
	_EntityTypeName[1085:1099]:      EntityTypeUser,
	_EntityTypeLowerName[1085:1099]: EntityTypeUser,
	_EntityTypeName[1099:1127]:      EntityTypeUserAccountAutoLiq,
	_EntityTypeLowerName[1099:1127]: EntityTypeUserAccountAutoLiq,
	_EntityTypeName[1127:1161]:      EntityTypeUserAccountPositionLimit,
	_EntityTypeLowerName[1127:1161]: EntityTypeUserAccountPositionLimit,
	_EntityTypeName[1161:1195]:      EntityTypeUserAccountRiskParameter,
	_EntityTypeLowerName[1161:1195]: EntityTypeUserAccountRiskParameter,
	_EntityTypeName[1195:1215]:      EntityTypeUserPlugin,
	_EntityTypeLowerName[1195:1215]: EntityTypeUserPlugin,
	_EntityTypeName[1215:1237]:      EntityTypeUserProperty,
	_EntityTypeLowerName[1215:1237]: EntityTypeUserProperty,
	_EntityTypeName[1237:1258]:      EntityTypeUserSession,
	_EntityTypeLowerName[1237:1258]: EntityTypeUserSession,
	_EntityTypeName[1258:1284]:      EntityTypeUserSessionStats,
	_EntityTypeLowerName[1258:1284]: EntityTypeUserSessionStats,
}

var _EntityTypeNames = []string{
	_EntityTypeName[0:21],
	_EntityTypeName[21:38],
	_EntityTypeName[38:65],
	_EntityTypeName[65:85],
	_EntityTypeName[85:111],
	_EntityTypeName[111:132],
	_EntityTypeName[132:156],
	_EntityTypeName[156:170],
	_EntityTypeName[170:191],
	_EntityTypeName[191:214],
	_EntityTypeName[214:231],
	_EntityTypeName[231:254],
	_EntityTypeName[254:275],
	_EntityTypeName[275:293],
	_EntityTypeName[293:316],
	_EntityTypeName[316:340],
	_EntityTypeName[340:366],
	_EntityTypeName[366:384],
	_EntityTypeName[384:406],
	_EntityTypeName[406:427],
	_EntityTypeName[427:445],
	_EntityTypeName[445:470],
	_EntityTypeName[470:484],
	_EntityTypeName[484:501],
	_EntityTypeName[501:519],
	_EntityTypeName[519:543],
	_EntityTypeName[543:575],
	_EntityTypeName[575:620],
	_EntityTypeName[620:656],
	_EntityTypeName[656:671],
	_EntityTypeName[671:694],
	_EntityTypeName[694:721],
	_EntityTypeName[721:748],
	_EntityTypeName[748:770],
	_EntityTypeName[770:792],
	_EntityTypeName[792:828],
	_EntityTypeName[828:846],
	_EntityTypeName[846:863],
	_EntityTypeName[863:886],
	_EntityTypeName[886:910],
	_EntityTypeName[910:928],
	_EntityTypeName[928:966],
	_EntityTypeName[966:992],
	_EntityTypeName[992:1019],
	_EntityTypeName[1019:1050],
	_EntityTypeName[1050:1085],
	_EntityTypeName[1085:1099],
	_EntityTypeName[1099:1127],
	_EntityTypeName[1127:1161],
	_EntityTypeName[1161:1195],
	_EntityTypeName[1195:1215],
	_EntityTypeName[1215:1237],
	_EntityTypeName[1237:1258],
	_EntityTypeName[1258:1284],
}

// EntityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EntityTypeString(s string) (EntityType, error) {
	if val, ok := _EntityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EntityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EntityType values", s)
}

// EntityTypeValues returns all values of the enum
func EntityTypeValues() []EntityType {
	return _EntityTypeValues
}

// EntityTypeStrings returns a slice of all String values of the enum
func EntityTypeStrings() []string {
	strs := make([]string, len(_EntityTypeNames))
	copy(strs, _EntityTypeNames)
	return strs
}

// IsAEntityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EntityType) IsAEntityType() bool {
	for _, v := range _EntityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EntityType
func (i EntityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EntityType
func (i *EntityType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EntityType should be a string, got %s", data)
	}

	var err error
	*i, err = EntityTypeString(s)
	return err
}
