// Code generated by "enumer -type EntityType -trimprefix EntityMsg -json"; DO NOT EDIT.

package tradovate

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EntityTypeName = "EntityTypeUnspecifiedEntityTypeAccountEntityTypeAccountRiskStatusEntityTypeAdminAlertEntityTypeAdminAlertSignalEntityTypeCashBalanceEntityTypeCashBalanceLogEntityTypeChatEntityTypeChatMessageEntityTypeClearingHouseEntityTypeCommandEntityTypeCommandReportEntityTypeContactInfoEntityTypeContractEntityTypeContractGroupEntityTypeContractMarginEntityTypeContractMaturityEntityTypeCurrencyEntityTypeCurrencyRateEntityTypeEntitlementEntityTypeExchangeEntityTypeExecutionReportEntityTypeFillEntityTypeFillFeeEntityTypeFillPairEntityTypeMarginSnapshotEntityTypeMarketDataSubscriptionEntityTypeMarketDataSubscriptionExchangeScopeEntityTypeMarketDataSubscriptionPlanEntityTypeOrderStrategyEntityTypeOrderStrategyLinkEntityTypeOrderStrategyTypeEntityTypeOrderVersionEntityTypeOrganizationEntityTypePermissionedAccountAutoLiqEntityTypePositionEntityTypeProductEntityTypeProductMarginEntityTypeProductSessionEntityTypePropertyEntityTypeSecondMarketDataSubscriptionEntityTypeSpreadDefinitionEntityTypeTradingPermissionEntityTypeTradovateSubscriptionEntityTypeTradovateSubscriptionPlanEntityTypeUserEntityTypeUserAccountAutoLiqEntityTypeUserAccountPositionLimitEntityTypeUserAccountRiskParameterEntityTypeUserPluginEntityTypeUserPropertyEntityTypeUserSessionEntityTypeUserSessionStats"

var _EntityTypeIndex = [...]uint16{0, 21, 38, 65, 85, 111, 132, 156, 170, 191, 214, 231, 254, 275, 293, 316, 340, 366, 384, 406, 427, 445, 470, 484, 501, 519, 543, 575, 620, 656, 679, 706, 733, 755, 777, 813, 831, 848, 871, 895, 913, 951, 977, 1004, 1035, 1070, 1084, 1112, 1146, 1180, 1200, 1222, 1243, 1269}

const _EntityTypeLowerName = "entitytypeunspecifiedentitytypeaccountentitytypeaccountriskstatusentitytypeadminalertentitytypeadminalertsignalentitytypecashbalanceentitytypecashbalancelogentitytypechatentitytypechatmessageentitytypeclearinghouseentitytypecommandentitytypecommandreportentitytypecontactinfoentitytypecontractentitytypecontractgroupentitytypecontractmarginentitytypecontractmaturityentitytypecurrencyentitytypecurrencyrateentitytypeentitlemententitytypeexchangeentitytypeexecutionreportentitytypefillentitytypefillfeeentitytypefillpairentitytypemarginsnapshotentitytypemarketdatasubscriptionentitytypemarketdatasubscriptionexchangescopeentitytypemarketdatasubscriptionplanentitytypeorderstrategyentitytypeorderstrategylinkentitytypeorderstrategytypeentitytypeorderversionentitytypeorganizationentitytypepermissionedaccountautoliqentitytypepositionentitytypeproductentitytypeproductmarginentitytypeproductsessionentitytypepropertyentitytypesecondmarketdatasubscriptionentitytypespreaddefinitionentitytypetradingpermissionentitytypetradovatesubscriptionentitytypetradovatesubscriptionplanentitytypeuserentitytypeuseraccountautoliqentitytypeuseraccountpositionlimitentitytypeuseraccountriskparameterentitytypeuserpluginentitytypeuserpropertyentitytypeusersessionentitytypeusersessionstats"

func (i EntityType) String() string {
	if i >= EntityType(len(_EntityTypeIndex)-1) {
		return fmt.Sprintf("EntityType(%d)", i)
	}
	return _EntityTypeName[_EntityTypeIndex[i]:_EntityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EntityTypeNoOp() {
	var x [1]struct{}
	_ = x[EntityTypeUnspecified-(0)]
	_ = x[EntityTypeAccount-(1)]
	_ = x[EntityTypeAccountRiskStatus-(2)]
	_ = x[EntityTypeAdminAlert-(3)]
	_ = x[EntityTypeAdminAlertSignal-(4)]
	_ = x[EntityTypeCashBalance-(5)]
	_ = x[EntityTypeCashBalanceLog-(6)]
	_ = x[EntityTypeChat-(7)]
	_ = x[EntityTypeChatMessage-(8)]
	_ = x[EntityTypeClearingHouse-(9)]
	_ = x[EntityTypeCommand-(10)]
	_ = x[EntityTypeCommandReport-(11)]
	_ = x[EntityTypeContactInfo-(12)]
	_ = x[EntityTypeContract-(13)]
	_ = x[EntityTypeContractGroup-(14)]
	_ = x[EntityTypeContractMargin-(15)]
	_ = x[EntityTypeContractMaturity-(16)]
	_ = x[EntityTypeCurrency-(17)]
	_ = x[EntityTypeCurrencyRate-(18)]
	_ = x[EntityTypeEntitlement-(19)]
	_ = x[EntityTypeExchange-(20)]
	_ = x[EntityTypeExecutionReport-(21)]
	_ = x[EntityTypeFill-(22)]
	_ = x[EntityTypeFillFee-(23)]
	_ = x[EntityTypeFillPair-(24)]
	_ = x[EntityTypeMarginSnapshot-(25)]
	_ = x[EntityTypeMarketDataSubscription-(26)]
	_ = x[EntityTypeMarketDataSubscriptionExchangeScope-(27)]
	_ = x[EntityTypeMarketDataSubscriptionPlan-(28)]
	_ = x[EntityTypeOrderStrategy-(29)]
	_ = x[EntityTypeOrderStrategyLink-(30)]
	_ = x[EntityTypeOrderStrategyType-(31)]
	_ = x[EntityTypeOrderVersion-(32)]
	_ = x[EntityTypeOrganization-(33)]
	_ = x[EntityTypePermissionedAccountAutoLiq-(34)]
	_ = x[EntityTypePosition-(35)]
	_ = x[EntityTypeProduct-(36)]
	_ = x[EntityTypeProductMargin-(37)]
	_ = x[EntityTypeProductSession-(38)]
	_ = x[EntityTypeProperty-(39)]
	_ = x[EntityTypeSecondMarketDataSubscription-(40)]
	_ = x[EntityTypeSpreadDefinition-(41)]
	_ = x[EntityTypeTradingPermission-(42)]
	_ = x[EntityTypeTradovateSubscription-(43)]
	_ = x[EntityTypeTradovateSubscriptionPlan-(44)]
	_ = x[EntityTypeUser-(45)]
	_ = x[EntityTypeUserAccountAutoLiq-(46)]
	_ = x[EntityTypeUserAccountPositionLimit-(47)]
	_ = x[EntityTypeUserAccountRiskParameter-(48)]
	_ = x[EntityTypeUserPlugin-(49)]
	_ = x[EntityTypeUserProperty-(50)]
	_ = x[EntityTypeUserSession-(51)]
	_ = x[EntityTypeUserSessionStats-(52)]
}

var _EntityTypeValues = []EntityType{EntityTypeUnspecified, EntityTypeAccount, EntityTypeAccountRiskStatus, EntityTypeAdminAlert, EntityTypeAdminAlertSignal, EntityTypeCashBalance, EntityTypeCashBalanceLog, EntityTypeChat, EntityTypeChatMessage, EntityTypeClearingHouse, EntityTypeCommand, EntityTypeCommandReport, EntityTypeContactInfo, EntityTypeContract, EntityTypeContractGroup, EntityTypeContractMargin, EntityTypeContractMaturity, EntityTypeCurrency, EntityTypeCurrencyRate, EntityTypeEntitlement, EntityTypeExchange, EntityTypeExecutionReport, EntityTypeFill, EntityTypeFillFee, EntityTypeFillPair, EntityTypeMarginSnapshot, EntityTypeMarketDataSubscription, EntityTypeMarketDataSubscriptionExchangeScope, EntityTypeMarketDataSubscriptionPlan, EntityTypeOrderStrategy, EntityTypeOrderStrategyLink, EntityTypeOrderStrategyType, EntityTypeOrderVersion, EntityTypeOrganization, EntityTypePermissionedAccountAutoLiq, EntityTypePosition, EntityTypeProduct, EntityTypeProductMargin, EntityTypeProductSession, EntityTypeProperty, EntityTypeSecondMarketDataSubscription, EntityTypeSpreadDefinition, EntityTypeTradingPermission, EntityTypeTradovateSubscription, EntityTypeTradovateSubscriptionPlan, EntityTypeUser, EntityTypeUserAccountAutoLiq, EntityTypeUserAccountPositionLimit, EntityTypeUserAccountRiskParameter, EntityTypeUserPlugin, EntityTypeUserProperty, EntityTypeUserSession, EntityTypeUserSessionStats}

var _EntityTypeNameToValueMap = map[string]EntityType{
	_EntityTypeName[0:21]:           EntityTypeUnspecified,
	_EntityTypeLowerName[0:21]:      EntityTypeUnspecified,
	_EntityTypeName[21:38]:          EntityTypeAccount,
	_EntityTypeLowerName[21:38]:     EntityTypeAccount,
	_EntityTypeName[38:65]:          EntityTypeAccountRiskStatus,
	_EntityTypeLowerName[38:65]:     EntityTypeAccountRiskStatus,
	_EntityTypeName[65:85]:          EntityTypeAdminAlert,
	_EntityTypeLowerName[65:85]:     EntityTypeAdminAlert,
	_EntityTypeName[85:111]:         EntityTypeAdminAlertSignal,
	_EntityTypeLowerName[85:111]:    EntityTypeAdminAlertSignal,
	_EntityTypeName[111:132]:        EntityTypeCashBalance,
	_EntityTypeLowerName[111:132]:   EntityTypeCashBalance,
	_EntityTypeName[132:156]:        EntityTypeCashBalanceLog,
	_EntityTypeLowerName[132:156]:   EntityTypeCashBalanceLog,
	_EntityTypeName[156:170]:        EntityTypeChat,
	_EntityTypeLowerName[156:170]:   EntityTypeChat,
	_EntityTypeName[170:191]:        EntityTypeChatMessage,
	_EntityTypeLowerName[170:191]:   EntityTypeChatMessage,
	_EntityTypeName[191:214]:        EntityTypeClearingHouse,
	_EntityTypeLowerName[191:214]:   EntityTypeClearingHouse,
	_EntityTypeName[214:231]:        EntityTypeCommand,
	_EntityTypeLowerName[214:231]:   EntityTypeCommand,
	_EntityTypeName[231:254]:        EntityTypeCommandReport,
	_EntityTypeLowerName[231:254]:   EntityTypeCommandReport,
	_EntityTypeName[254:275]:        EntityTypeContactInfo,
	_EntityTypeLowerName[254:275]:   EntityTypeContactInfo,
	_EntityTypeName[275:293]:        EntityTypeContract,
	_EntityTypeLowerName[275:293]:   EntityTypeContract,
	_EntityTypeName[293:316]:        EntityTypeContractGroup,
	_EntityTypeLowerName[293:316]:   EntityTypeContractGroup,
	_EntityTypeName[316:340]:        EntityTypeContractMargin,
	_EntityTypeLowerName[316:340]:   EntityTypeContractMargin,
	_EntityTypeName[340:366]:        EntityTypeContractMaturity,
	_EntityTypeLowerName[340:366]:   EntityTypeContractMaturity,
	_EntityTypeName[366:384]:        EntityTypeCurrency,
	_EntityTypeLowerName[366:384]:   EntityTypeCurrency,
	_EntityTypeName[384:406]:        EntityTypeCurrencyRate,
	_EntityTypeLowerName[384:406]:   EntityTypeCurrencyRate,
	_EntityTypeName[406:427]:        EntityTypeEntitlement,
	_EntityTypeLowerName[406:427]:   EntityTypeEntitlement,
	_EntityTypeName[427:445]:        EntityTypeExchange,
	_EntityTypeLowerName[427:445]:   EntityTypeExchange,
	_EntityTypeName[445:470]:        EntityTypeExecutionReport,
	_EntityTypeLowerName[445:470]:   EntityTypeExecutionReport,
	_EntityTypeName[470:484]:        EntityTypeFill,
	_EntityTypeLowerName[470:484]:   EntityTypeFill,
	_EntityTypeName[484:501]:        EntityTypeFillFee,
	_EntityTypeLowerName[484:501]:   EntityTypeFillFee,
	_EntityTypeName[501:519]:        EntityTypeFillPair,
	_EntityTypeLowerName[501:519]:   EntityTypeFillPair,
	_EntityTypeName[519:543]:        EntityTypeMarginSnapshot,
	_EntityTypeLowerName[519:543]:   EntityTypeMarginSnapshot,
	_EntityTypeName[543:575]:        EntityTypeMarketDataSubscription,
	_EntityTypeLowerName[543:575]:   EntityTypeMarketDataSubscription,
	_EntityTypeName[575:620]:        EntityTypeMarketDataSubscriptionExchangeScope,
	_EntityTypeLowerName[575:620]:   EntityTypeMarketDataSubscriptionExchangeScope,
	_EntityTypeName[620:656]:        EntityTypeMarketDataSubscriptionPlan,
	_EntityTypeLowerName[620:656]:   EntityTypeMarketDataSubscriptionPlan,
	_EntityTypeName[656:679]:        EntityTypeOrderStrategy,
	_EntityTypeLowerName[656:679]:   EntityTypeOrderStrategy,
	_EntityTypeName[679:706]:        EntityTypeOrderStrategyLink,
	_EntityTypeLowerName[679:706]:   EntityTypeOrderStrategyLink,
	_EntityTypeName[706:733]:        EntityTypeOrderStrategyType,
	_EntityTypeLowerName[706:733]:   EntityTypeOrderStrategyType,
	_EntityTypeName[733:755]:        EntityTypeOrderVersion,
	_EntityTypeLowerName[733:755]:   EntityTypeOrderVersion,
	_EntityTypeName[755:777]:        EntityTypeOrganization,
	_EntityTypeLowerName[755:777]:   EntityTypeOrganization,
	_EntityTypeName[777:813]:        EntityTypePermissionedAccountAutoLiq,
	_EntityTypeLowerName[777:813]:   EntityTypePermissionedAccountAutoLiq,
	_EntityTypeName[813:831]:        EntityTypePosition,
	_EntityTypeLowerName[813:831]:   EntityTypePosition,
	_EntityTypeName[831:848]:        EntityTypeProduct,
	_EntityTypeLowerName[831:848]:   EntityTypeProduct,
	_EntityTypeName[848:871]:        EntityTypeProductMargin,
	_EntityTypeLowerName[848:871]:   EntityTypeProductMargin,
	_EntityTypeName[871:895]:        EntityTypeProductSession,
	_EntityTypeLowerName[871:895]:   EntityTypeProductSession,
	_EntityTypeName[895:913]:        EntityTypeProperty,
	_EntityTypeLowerName[895:913]:   EntityTypeProperty,
	_EntityTypeName[913:951]:        EntityTypeSecondMarketDataSubscription,
	_EntityTypeLowerName[913:951]:   EntityTypeSecondMarketDataSubscription,
	_EntityTypeName[951:977]:        EntityTypeSpreadDefinition,
	_EntityTypeLowerName[951:977]:   EntityTypeSpreadDefinition,
	_EntityTypeName[977:1004]:       EntityTypeTradingPermission,
	_EntityTypeLowerName[977:1004]:  EntityTypeTradingPermission,
	_EntityTypeName[1004:1035]:      EntityTypeTradovateSubscription,
	_EntityTypeLowerName[1004:1035]: EntityTypeTradovateSubscription,
	_EntityTypeName[1035:1070]:      EntityTypeTradovateSubscriptionPlan,
	_EntityTypeLowerName[1035:1070]: EntityTypeTradovateSubscriptionPlan,
	_EntityTypeName[1070:1084]:      EntityTypeUser,
	_EntityTypeLowerName[1070:1084]: EntityTypeUser,
	_EntityTypeName[1084:1112]:      EntityTypeUserAccountAutoLiq,
	_EntityTypeLowerName[1084:1112]: EntityTypeUserAccountAutoLiq,
	_EntityTypeName[1112:1146]:      EntityTypeUserAccountPositionLimit,
	_EntityTypeLowerName[1112:1146]: EntityTypeUserAccountPositionLimit,
	_EntityTypeName[1146:1180]:      EntityTypeUserAccountRiskParameter,
	_EntityTypeLowerName[1146:1180]: EntityTypeUserAccountRiskParameter,
	_EntityTypeName[1180:1200]:      EntityTypeUserPlugin,
	_EntityTypeLowerName[1180:1200]: EntityTypeUserPlugin,
	_EntityTypeName[1200:1222]:      EntityTypeUserProperty,
	_EntityTypeLowerName[1200:1222]: EntityTypeUserProperty,
	_EntityTypeName[1222:1243]:      EntityTypeUserSession,
	_EntityTypeLowerName[1222:1243]: EntityTypeUserSession,
	_EntityTypeName[1243:1269]:      EntityTypeUserSessionStats,
	_EntityTypeLowerName[1243:1269]: EntityTypeUserSessionStats,
}

var _EntityTypeNames = []string{
	_EntityTypeName[0:21],
	_EntityTypeName[21:38],
	_EntityTypeName[38:65],
	_EntityTypeName[65:85],
	_EntityTypeName[85:111],
	_EntityTypeName[111:132],
	_EntityTypeName[132:156],
	_EntityTypeName[156:170],
	_EntityTypeName[170:191],
	_EntityTypeName[191:214],
	_EntityTypeName[214:231],
	_EntityTypeName[231:254],
	_EntityTypeName[254:275],
	_EntityTypeName[275:293],
	_EntityTypeName[293:316],
	_EntityTypeName[316:340],
	_EntityTypeName[340:366],
	_EntityTypeName[366:384],
	_EntityTypeName[384:406],
	_EntityTypeName[406:427],
	_EntityTypeName[427:445],
	_EntityTypeName[445:470],
	_EntityTypeName[470:484],
	_EntityTypeName[484:501],
	_EntityTypeName[501:519],
	_EntityTypeName[519:543],
	_EntityTypeName[543:575],
	_EntityTypeName[575:620],
	_EntityTypeName[620:656],
	_EntityTypeName[656:679],
	_EntityTypeName[679:706],
	_EntityTypeName[706:733],
	_EntityTypeName[733:755],
	_EntityTypeName[755:777],
	_EntityTypeName[777:813],
	_EntityTypeName[813:831],
	_EntityTypeName[831:848],
	_EntityTypeName[848:871],
	_EntityTypeName[871:895],
	_EntityTypeName[895:913],
	_EntityTypeName[913:951],
	_EntityTypeName[951:977],
	_EntityTypeName[977:1004],
	_EntityTypeName[1004:1035],
	_EntityTypeName[1035:1070],
	_EntityTypeName[1070:1084],
	_EntityTypeName[1084:1112],
	_EntityTypeName[1112:1146],
	_EntityTypeName[1146:1180],
	_EntityTypeName[1180:1200],
	_EntityTypeName[1200:1222],
	_EntityTypeName[1222:1243],
	_EntityTypeName[1243:1269],
}

// EntityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EntityTypeString(s string) (EntityType, error) {
	if val, ok := _EntityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EntityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EntityType values", s)
}

// EntityTypeValues returns all values of the enum
func EntityTypeValues() []EntityType {
	return _EntityTypeValues
}

// EntityTypeStrings returns a slice of all String values of the enum
func EntityTypeStrings() []string {
	strs := make([]string, len(_EntityTypeNames))
	copy(strs, _EntityTypeNames)
	return strs
}

// IsAEntityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EntityType) IsAEntityType() bool {
	for _, v := range _EntityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EntityType
func (i EntityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EntityType
func (i *EntityType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EntityType should be a string, got %s", data)
	}

	var err error
	*i, err = EntityTypeString(s)
	return err
}
