// Code generated by interfacer; DO NOT EDIT

package tradovate

import (
	"context"
)

// RESTInterface is an interface generated for "github.com/AnthonyHewins/tradovate.Client".
type RESTInterface interface {
	SetToken(*Token)
	Token(context.Context) (*Token, error)
}
