// Code generated by "enumer -type OrderErrReason -trimprefix OrderErrReason -json"; DO NOT EDIT.

package tradovate

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _OrderErrReasonName = "AccountUnspecifiedAccountClosedAdvancedTrailingStopUnsupportedAnotherCommandPendingBackMonthProhibitedExecutionProviderNotConfiguredExecutionProviderUnavailableInvalidContractInvalidPriceLiquidationOnlyLiquidationOnlyBeforeExpirationMaxOrderQtyIsNotSpecifiedMaxOrderQtyLimitReachedMaxPosLimitMisconfiguredMaxPosLimitReachedMaxTotalPosLimitReachedMultipleAccountPlanRequiredNoQuoteNotEnoughLiquidityOtherExecutionRelatedParentRejectedRiskCheckTimeoutSessionClosedSuccessTooLateTradingLockedTrailingStopNonOrderQtyModifyUnauthorizedUnknownReasonUnsupported"

var _OrderErrReasonIndex = [...]uint16{0, 18, 31, 62, 83, 102, 132, 160, 175, 187, 202, 233, 258, 281, 305, 323, 346, 373, 380, 398, 419, 433, 449, 462, 469, 476, 489, 518, 530, 543, 554}

const _OrderErrReasonLowerName = "accountunspecifiedaccountclosedadvancedtrailingstopunsupportedanothercommandpendingbackmonthprohibitedexecutionprovidernotconfiguredexecutionproviderunavailableinvalidcontractinvalidpriceliquidationonlyliquidationonlybeforeexpirationmaxorderqtyisnotspecifiedmaxorderqtylimitreachedmaxposlimitmisconfiguredmaxposlimitreachedmaxtotalposlimitreachedmultipleaccountplanrequirednoquotenotenoughliquidityotherexecutionrelatedparentrejectedriskchecktimeoutsessionclosedsuccesstoolatetradinglockedtrailingstopnonorderqtymodifyunauthorizedunknownreasonunsupported"

func (i OrderErrReason) String() string {
	if i >= OrderErrReason(len(_OrderErrReasonIndex)-1) {
		return fmt.Sprintf("OrderErrReason(%d)", i)
	}
	return _OrderErrReasonName[_OrderErrReasonIndex[i]:_OrderErrReasonIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OrderErrReasonNoOp() {
	var x [1]struct{}
	_ = x[OrderErrReasonAccountUnspecified-(0)]
	_ = x[OrderErrReasonAccountClosed-(1)]
	_ = x[OrderErrReasonAdvancedTrailingStopUnsupported-(2)]
	_ = x[OrderErrReasonAnotherCommandPending-(3)]
	_ = x[OrderErrReasonBackMonthProhibited-(4)]
	_ = x[OrderErrReasonExecutionProviderNotConfigured-(5)]
	_ = x[OrderErrReasonExecutionProviderUnavailable-(6)]
	_ = x[OrderErrReasonInvalidContract-(7)]
	_ = x[OrderErrReasonInvalidPrice-(8)]
	_ = x[OrderErrReasonLiquidationOnly-(9)]
	_ = x[OrderErrReasonLiquidationOnlyBeforeExpiration-(10)]
	_ = x[OrderErrReasonMaxOrderQtyIsNotSpecified-(11)]
	_ = x[OrderErrReasonMaxOrderQtyLimitReached-(12)]
	_ = x[OrderErrReasonMaxPosLimitMisconfigured-(13)]
	_ = x[OrderErrReasonMaxPosLimitReached-(14)]
	_ = x[OrderErrReasonMaxTotalPosLimitReached-(15)]
	_ = x[OrderErrReasonMultipleAccountPlanRequired-(16)]
	_ = x[OrderErrReasonNoQuote-(17)]
	_ = x[OrderErrReasonNotEnoughLiquidity-(18)]
	_ = x[OrderErrReasonOtherExecutionRelated-(19)]
	_ = x[OrderErrReasonParentRejected-(20)]
	_ = x[OrderErrReasonRiskCheckTimeout-(21)]
	_ = x[OrderErrReasonSessionClosed-(22)]
	_ = x[OrderErrReasonSuccess-(23)]
	_ = x[OrderErrReasonTooLate-(24)]
	_ = x[OrderErrReasonTradingLocked-(25)]
	_ = x[OrderErrReasonTrailingStopNonOrderQtyModify-(26)]
	_ = x[OrderErrReasonUnauthorized-(27)]
	_ = x[OrderErrReasonUnknownReason-(28)]
	_ = x[OrderErrReasonUnsupported-(29)]
}

var _OrderErrReasonValues = []OrderErrReason{OrderErrReasonAccountUnspecified, OrderErrReasonAccountClosed, OrderErrReasonAdvancedTrailingStopUnsupported, OrderErrReasonAnotherCommandPending, OrderErrReasonBackMonthProhibited, OrderErrReasonExecutionProviderNotConfigured, OrderErrReasonExecutionProviderUnavailable, OrderErrReasonInvalidContract, OrderErrReasonInvalidPrice, OrderErrReasonLiquidationOnly, OrderErrReasonLiquidationOnlyBeforeExpiration, OrderErrReasonMaxOrderQtyIsNotSpecified, OrderErrReasonMaxOrderQtyLimitReached, OrderErrReasonMaxPosLimitMisconfigured, OrderErrReasonMaxPosLimitReached, OrderErrReasonMaxTotalPosLimitReached, OrderErrReasonMultipleAccountPlanRequired, OrderErrReasonNoQuote, OrderErrReasonNotEnoughLiquidity, OrderErrReasonOtherExecutionRelated, OrderErrReasonParentRejected, OrderErrReasonRiskCheckTimeout, OrderErrReasonSessionClosed, OrderErrReasonSuccess, OrderErrReasonTooLate, OrderErrReasonTradingLocked, OrderErrReasonTrailingStopNonOrderQtyModify, OrderErrReasonUnauthorized, OrderErrReasonUnknownReason, OrderErrReasonUnsupported}

var _OrderErrReasonNameToValueMap = map[string]OrderErrReason{
	_OrderErrReasonName[0:18]:         OrderErrReasonAccountUnspecified,
	_OrderErrReasonLowerName[0:18]:    OrderErrReasonAccountUnspecified,
	_OrderErrReasonName[18:31]:        OrderErrReasonAccountClosed,
	_OrderErrReasonLowerName[18:31]:   OrderErrReasonAccountClosed,
	_OrderErrReasonName[31:62]:        OrderErrReasonAdvancedTrailingStopUnsupported,
	_OrderErrReasonLowerName[31:62]:   OrderErrReasonAdvancedTrailingStopUnsupported,
	_OrderErrReasonName[62:83]:        OrderErrReasonAnotherCommandPending,
	_OrderErrReasonLowerName[62:83]:   OrderErrReasonAnotherCommandPending,
	_OrderErrReasonName[83:102]:       OrderErrReasonBackMonthProhibited,
	_OrderErrReasonLowerName[83:102]:  OrderErrReasonBackMonthProhibited,
	_OrderErrReasonName[102:132]:      OrderErrReasonExecutionProviderNotConfigured,
	_OrderErrReasonLowerName[102:132]: OrderErrReasonExecutionProviderNotConfigured,
	_OrderErrReasonName[132:160]:      OrderErrReasonExecutionProviderUnavailable,
	_OrderErrReasonLowerName[132:160]: OrderErrReasonExecutionProviderUnavailable,
	_OrderErrReasonName[160:175]:      OrderErrReasonInvalidContract,
	_OrderErrReasonLowerName[160:175]: OrderErrReasonInvalidContract,
	_OrderErrReasonName[175:187]:      OrderErrReasonInvalidPrice,
	_OrderErrReasonLowerName[175:187]: OrderErrReasonInvalidPrice,
	_OrderErrReasonName[187:202]:      OrderErrReasonLiquidationOnly,
	_OrderErrReasonLowerName[187:202]: OrderErrReasonLiquidationOnly,
	_OrderErrReasonName[202:233]:      OrderErrReasonLiquidationOnlyBeforeExpiration,
	_OrderErrReasonLowerName[202:233]: OrderErrReasonLiquidationOnlyBeforeExpiration,
	_OrderErrReasonName[233:258]:      OrderErrReasonMaxOrderQtyIsNotSpecified,
	_OrderErrReasonLowerName[233:258]: OrderErrReasonMaxOrderQtyIsNotSpecified,
	_OrderErrReasonName[258:281]:      OrderErrReasonMaxOrderQtyLimitReached,
	_OrderErrReasonLowerName[258:281]: OrderErrReasonMaxOrderQtyLimitReached,
	_OrderErrReasonName[281:305]:      OrderErrReasonMaxPosLimitMisconfigured,
	_OrderErrReasonLowerName[281:305]: OrderErrReasonMaxPosLimitMisconfigured,
	_OrderErrReasonName[305:323]:      OrderErrReasonMaxPosLimitReached,
	_OrderErrReasonLowerName[305:323]: OrderErrReasonMaxPosLimitReached,
	_OrderErrReasonName[323:346]:      OrderErrReasonMaxTotalPosLimitReached,
	_OrderErrReasonLowerName[323:346]: OrderErrReasonMaxTotalPosLimitReached,
	_OrderErrReasonName[346:373]:      OrderErrReasonMultipleAccountPlanRequired,
	_OrderErrReasonLowerName[346:373]: OrderErrReasonMultipleAccountPlanRequired,
	_OrderErrReasonName[373:380]:      OrderErrReasonNoQuote,
	_OrderErrReasonLowerName[373:380]: OrderErrReasonNoQuote,
	_OrderErrReasonName[380:398]:      OrderErrReasonNotEnoughLiquidity,
	_OrderErrReasonLowerName[380:398]: OrderErrReasonNotEnoughLiquidity,
	_OrderErrReasonName[398:419]:      OrderErrReasonOtherExecutionRelated,
	_OrderErrReasonLowerName[398:419]: OrderErrReasonOtherExecutionRelated,
	_OrderErrReasonName[419:433]:      OrderErrReasonParentRejected,
	_OrderErrReasonLowerName[419:433]: OrderErrReasonParentRejected,
	_OrderErrReasonName[433:449]:      OrderErrReasonRiskCheckTimeout,
	_OrderErrReasonLowerName[433:449]: OrderErrReasonRiskCheckTimeout,
	_OrderErrReasonName[449:462]:      OrderErrReasonSessionClosed,
	_OrderErrReasonLowerName[449:462]: OrderErrReasonSessionClosed,
	_OrderErrReasonName[462:469]:      OrderErrReasonSuccess,
	_OrderErrReasonLowerName[462:469]: OrderErrReasonSuccess,
	_OrderErrReasonName[469:476]:      OrderErrReasonTooLate,
	_OrderErrReasonLowerName[469:476]: OrderErrReasonTooLate,
	_OrderErrReasonName[476:489]:      OrderErrReasonTradingLocked,
	_OrderErrReasonLowerName[476:489]: OrderErrReasonTradingLocked,
	_OrderErrReasonName[489:518]:      OrderErrReasonTrailingStopNonOrderQtyModify,
	_OrderErrReasonLowerName[489:518]: OrderErrReasonTrailingStopNonOrderQtyModify,
	_OrderErrReasonName[518:530]:      OrderErrReasonUnauthorized,
	_OrderErrReasonLowerName[518:530]: OrderErrReasonUnauthorized,
	_OrderErrReasonName[530:543]:      OrderErrReasonUnknownReason,
	_OrderErrReasonLowerName[530:543]: OrderErrReasonUnknownReason,
	_OrderErrReasonName[543:554]:      OrderErrReasonUnsupported,
	_OrderErrReasonLowerName[543:554]: OrderErrReasonUnsupported,
}

var _OrderErrReasonNames = []string{
	_OrderErrReasonName[0:18],
	_OrderErrReasonName[18:31],
	_OrderErrReasonName[31:62],
	_OrderErrReasonName[62:83],
	_OrderErrReasonName[83:102],
	_OrderErrReasonName[102:132],
	_OrderErrReasonName[132:160],
	_OrderErrReasonName[160:175],
	_OrderErrReasonName[175:187],
	_OrderErrReasonName[187:202],
	_OrderErrReasonName[202:233],
	_OrderErrReasonName[233:258],
	_OrderErrReasonName[258:281],
	_OrderErrReasonName[281:305],
	_OrderErrReasonName[305:323],
	_OrderErrReasonName[323:346],
	_OrderErrReasonName[346:373],
	_OrderErrReasonName[373:380],
	_OrderErrReasonName[380:398],
	_OrderErrReasonName[398:419],
	_OrderErrReasonName[419:433],
	_OrderErrReasonName[433:449],
	_OrderErrReasonName[449:462],
	_OrderErrReasonName[462:469],
	_OrderErrReasonName[469:476],
	_OrderErrReasonName[476:489],
	_OrderErrReasonName[489:518],
	_OrderErrReasonName[518:530],
	_OrderErrReasonName[530:543],
	_OrderErrReasonName[543:554],
}

// OrderErrReasonString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OrderErrReasonString(s string) (OrderErrReason, error) {
	if val, ok := _OrderErrReasonNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OrderErrReasonNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OrderErrReason values", s)
}

// OrderErrReasonValues returns all values of the enum
func OrderErrReasonValues() []OrderErrReason {
	return _OrderErrReasonValues
}

// OrderErrReasonStrings returns a slice of all String values of the enum
func OrderErrReasonStrings() []string {
	strs := make([]string, len(_OrderErrReasonNames))
	copy(strs, _OrderErrReasonNames)
	return strs
}

// IsAOrderErrReason returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OrderErrReason) IsAOrderErrReason() bool {
	for _, v := range _OrderErrReasonValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for OrderErrReason
func (i OrderErrReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OrderErrReason
func (i *OrderErrReason) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("OrderErrReason should be a string, got %s", data)
	}

	var err error
	*i, err = OrderErrReasonString(s)
	return err
}
