// Code generated by interfacer; DO NOT EDIT

package tradovate

import (
	"context"
)

// RESTInterface is an interface generated for "github.com/AnthonyHewins/tradovate.REST".
type RESTInterface interface {
	Order(context.Context)
	SetToken(*Token)
	Token(context.Context) (*Token, error)
}
