// Code generated by interfacer; DO NOT EDIT

package tradovate

import (
	"context"
)

// SocketInterface is an interface generated for "github.com/AnthonyHewins/tradovate.Socket".
type SocketInterface interface {
	Order(context.Context)
}
