// Code generated by "enumer -type Tif -trimprefix Tif -json"; DO NOT EDIT.

package tradovate

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TifName = "UnspecifiedDayFOKGTCGTDIOC"

var _TifIndex = [...]uint8{0, 11, 14, 17, 20, 23, 26}

const _TifLowerName = "unspecifieddayfokgtcgtdioc"

func (i Tif) String() string {
	if i >= Tif(len(_TifIndex)-1) {
		return fmt.Sprintf("Tif(%d)", i)
	}
	return _TifName[_TifIndex[i]:_TifIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TifNoOp() {
	var x [1]struct{}
	_ = x[TifUnspecified-(0)]
	_ = x[TifDay-(1)]
	_ = x[TifFOK-(2)]
	_ = x[TifGTC-(3)]
	_ = x[TifGTD-(4)]
	_ = x[TifIOC-(5)]
}

var _TifValues = []Tif{TifUnspecified, TifDay, TifFOK, TifGTC, TifGTD, TifIOC}

var _TifNameToValueMap = map[string]Tif{
	_TifName[0:11]:       TifUnspecified,
	_TifLowerName[0:11]:  TifUnspecified,
	_TifName[11:14]:      TifDay,
	_TifLowerName[11:14]: TifDay,
	_TifName[14:17]:      TifFOK,
	_TifLowerName[14:17]: TifFOK,
	_TifName[17:20]:      TifGTC,
	_TifLowerName[17:20]: TifGTC,
	_TifName[20:23]:      TifGTD,
	_TifLowerName[20:23]: TifGTD,
	_TifName[23:26]:      TifIOC,
	_TifLowerName[23:26]: TifIOC,
}

var _TifNames = []string{
	_TifName[0:11],
	_TifName[11:14],
	_TifName[14:17],
	_TifName[17:20],
	_TifName[20:23],
	_TifName[23:26],
}

// TifString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TifString(s string) (Tif, error) {
	if val, ok := _TifNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TifNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Tif values", s)
}

// TifValues returns all values of the enum
func TifValues() []Tif {
	return _TifValues
}

// TifStrings returns a slice of all String values of the enum
func TifStrings() []string {
	strs := make([]string, len(_TifNames))
	copy(strs, _TifNames)
	return strs
}

// IsATif returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Tif) IsATif() bool {
	for _, v := range _TifValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Tif
func (i Tif) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Tif
func (i *Tif) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Tif should be a string, got %s", data)
	}

	var err error
	*i, err = TifString(s)
	return err
}
